{% set name = "scramaligner" %}
{% set version = "2.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

# source:
#   url: https://github.com/username/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
#   sha256: your_sha256_checksum_here

build:
  number: 0
  script_env:
    - GOPATH
  # script: build.sh  # Add the build script
  skip: true  # [not linux]

requirements:
  host:
    - python
    - pip
    - go
  run:
    - python
    - matplotlib
    - seaborn
    - numpy
    - pandas

test:
  commands:
    - scram2 --help
    - adaptTrim --help
    - scram2Plot --help

about:
  home: https://github.com/username/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A bioinformatics application combining Go and Python scripts
  description: |
    This application is a bioinformatics tool that combines a Go-based app and Python scripts for processing and analyzing biological data. It utilizes the Go programming language for the main application and Python scripts for additional functionality.
  doc_url: https://github.com/username/{{ name }}/wiki
  dev_url: https://github.com/username/{{ name }}/issues

extra:
  identifiers:
    - doi:your_doi_here
    - pmid:your_pmid_here